### ISSUE TITLE
The order of tracker corners isn't always consistent

### ISSUE THREAD

**Issue by GavinJoyce** [damianofalcioni/js-aruco2#2]
Hi,

I notices a difference between `js-aruco` and `js-aruco2` in how corners are ordered.

In my testing, it seems that `js-aruco` always presents the tracker corners in a consistent fashion - the top left corner of the tracker always appears first. The order of corners in `js-aruco2` seems to change based on the orientation of the tracker.

Here's a video showing the difference (`js-aruco` on the left, `js-aruco2` on the right):

https://user-images.githubusercontent.com/2526/130999565-9c638466-3d42-48a8-9332-0fed23824140.mp4

Notice that with `js-aruco`, the first corner is fixed:

<img width="170" alt="Screenshot 2021-08-26 at 17 20 44" src="https://user-images.githubusercontent.com/2526/130999822-dbd154fa-e36b-4206-b1a3-14e01c118100.png">

And with `js-aruco2`, it flips depending on the orientation of the tracker:

<img width="151" alt="Screenshot 2021-08-26 at 17 21 10" src="https://user-images.githubusercontent.com/2526/130999899-07359453-163c-4bbe-bde4-21a8a0424608.png">

<img width="189" alt="Screenshot 2021-08-26 at 17 21 16" src="https://user-images.githubusercontent.com/2526/130999909-b78c831d-f7a3-4a56-9cf3-cea867d0e07a.png">

**Comment by GavinJoyce** [comment]
@damianofalcioni Please let me know if the possible cause of this is obvious to you. I'm happy to work on a fix, your pointers might save me some time. Thanks

**Comment by GavinJoyce** [comment]
The issue seems to have been introduced in https://github.com/damianofalcioni/js-aruco2/commit/07303184d2d18c484b594e9157edc50fb46f70f4

**Comment by damianofalcioni** [comment]
Hi Gavin,
thanks for the notification. 
The inconsistency has been fixed now (https://github.com/damianofalcioni/js-aruco2/commit/90ae934d37153542d320d23a027922d437b7b8a1) and you can check it in the live demo.

Best Regards,
Damiano

**Comment by GavinJoyce** [comment]
I just verified, corners are working perfectly now. Thanks Damiano!
