### ISSUE TITLE
Which dictionary should I choose?

### ISSUE THREAD

**Issue by talip-b** [damianofalcioni/js-aruco2#4]
Hi,
I don't know when to use dictionaries ARUCO_MIP_36h12 and ARUCO.
Which one for the aruco.DICT_4X4_1000 dictionary in Python-Opencv
or which one should i use for aruco.DICT_7X7_50.
What I need is the priority of fast recognition in low resolution on mobile phones.
I would appreciate if you can provide further information on which dictionary should be used for fast recognition and which dictionary should be used for high accuracy.
thanks.

**Comment by damianofalcioni** [comment]
Hi,
for high accuracy you should use ARUCO_MIP_36h12 as it as the best error correction rate (12 bit distance).
The aruco.DICT_4X4_1000 in opencv is the same as this https://github.com/damianofalcioni/js-aruco2/blob/master/src/dictionaries/aruco_4x4_1000.js . You can see other dictionary in this folder and the name is quite explicit. 
The aruco.DICT_7X7_50 has not been imported.

Hope this helps
