### ISSUE TITLE
Issue with high res images 

### ISSUE THREAD

**Issue by dsilverston** [damianofalcioni/js-aruco2#5]
Hi Damiano-

I've been using your library for a mobile app, and it's been very helpful. However, something weird happens when I pass in high res images taken on IPad- the detector recognizes the markers when they're far away enough, but when they're close, it does not recognize them, which seems strange. I'm using the 4x4 library, and the pictures are 4032 x 3024 on IPad. Let me know if you think I need to downscale the image, or pass in a different hamming number (which I tried increasing), or use a different dictionary. 

Thanks a lot!
Danny

**Comment by damianofalcioni** [comment]
Hi Danny,
I think you have to play with this 0.01 value here https://github.com/damianofalcioni/js-aruco2/blob/4c6717b979a3f092ec290acdcf07e43731adbc7c/src/aruco.js#L271
accordingly to this StackOverflow post: https://stackoverflow.com/questions/35936397/marker-detection-on-paper-sheet-using-javascript
